HOME = "/home/pi/PeB"
passMy = "Mysqlpass"   # la passoword per MySql 
Fistant ="/var/www/istant.txt"
MyMail = 'pimail@gmail.com' # un' eventuale email configurata per il raspberry
MyMailPW = 'password' #password per l'email del raspberry
ToMail = 'tuaemail@xxx.xx' # E-mail dove inviare gli alert
enEmail = False  # abilita invio e-mail
enEvent= False   # abilita eventi da moduli
io = 1  # indirizzo raspberry  
net = 2 # rete 433
pwd = 5 # password 433
alert = 3000 # soglia per far scattare alert da scambio !!!
Salert = 1500 # soglia per riattivare invio alert
mqttEn = True
mqttUser = 'demo'
mqttPw = 'demopw'
mqttHost = 'localhost'
mqttPort = 1883
